-- E-commerce schema design
CREATE TABLE customers (
  customer_id   NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  name          VARCHAR2(100) NOT NULL,
  email         VARCHAR2(150) UNIQUE NOT NULL,
  created_on    TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE TABLE categories (
  category_id   NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  name          VARCHAR2(100) NOT NULL
);

CREATE TABLE products (
  product_id    NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  name          VARCHAR2(200) NOT NULL,
  description   CLOB,
  price         NUMBER(10,2) NOT NULL,
  category_id   NUMBER REFERENCES categories(category_id)
);

CREATE TABLE orders (
  order_id      NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  customer_id   NUMBER REFERENCES customers(customer_id),
  order_date    TIMESTAMP DEFAULT SYSTIMESTAMP,
  status        VARCHAR2(20) DEFAULT 'NEW'
);

CREATE TABLE order_items (
  order_item_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  order_id      NUMBER REFERENCES orders(order_id),
  product_id    NUMBER REFERENCES products(product_id),
  quantity      NUMBER(5) NOT NULL,
  unit_price    NUMBER(10,2) NOT NULL
);

CREATE INDEX idx_orders_customer ON orders(customer_id);
CREATE INDEX idx_items_order   ON order_items(order_id);
